version: '3.8'

services:
  node1:
    image: ghcr.io/kryptokrona/kryptokrona-testnet
    container_name: kryptokrona-node1
    command: >
      /bin/sh -c " ./src/kryptokronad  --data-dir src/blockloc  --add-exclusive-node 172.10.1.2:10001  --add-exclusive-node 172.10.1.3:10002  --p2p-bind-port 10000  --rpc-bind-port 20000  --rpc-bind-ip 172.10.1.1 --log-level 3 "
    ports:
      - "10000:10000"
      - "20000:20000"
    networks:
      testnet:
        ipv4_address: 172.10.1.1

  node2:
    image: ghcr.io/kryptokrona/kryptokrona-testnet
    container_name: kryptokrona-node2
    command: >
      /bin/sh -c " ./src/kryptokronad  --data-dir src/blockloc  --add-exclusive-node 172.10.1.1:10000  --add-exclusive-node 172.10.1.3:10002  --p2p-bind-port 10001  --rpc-bind-port 20001  --rpc-bind-ip 172.10.1.2 --log-level 3 "
    ports:
      - "10001:10001"
      - "20001:20001"
    networks:
      testnet:
        ipv4_address: 172.10.1.2

  node3:
    image: ghcr.io/kryptokrona/kryptokrona-testnet
    container_name: kryptokrona-node3
    command: >
      /bin/sh -c " ./src/kryptokronad  --data-dir src/blockloc  --add-exclusive-node 172.10.1.1:10000  --add-exclusive-node 172.10.1.2:10001  --p2p-bind-port 10002  --rpc-bind-port 20002  --rpc-bind-ip 172.10.1.3 --log-level 3 "
    ports:
      - "10002:10002"
      - "20002:20002"
    networks:
      testnet:
        ipv4_address: 172.10.1.3

  miner1:
    image: ghcr.io/kryptokrona/kryptokrona-testnet
    container_name: kryptokrona-miner1
    command: >
      /bin/sh -c " chmod 0644 /etc/cron.d/miner-cron && crontab /etc/cron.d/miner-cron && touch /var/log/cron.log && cron -f && tail -f /var/log/cron.log"
    volumes:
      - ./scripts/testnet/miner-cron:/etc/cron.d/miner-cron
    depends_on:
      - node1
      - node2
      - node3
    networks:
      testnet:
        ipv4_address: 172.10.1.4

networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.10.1.0/16"
